---
- name: Deploy Docker containers
  hosts: all
  become: yes

  tasks:

    - name: Pull Nginx image
      community.docker.docker_image:
        name: nginx
        tag: "1.27.5"
        source: pull

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx-app
        image: nginx:1.27.5
        state: started
        restart_policy: always
        published_ports:
          - "8081:80"

    - name: Pull Redis image
      community.docker.docker_image:
        name: redis
        tag: "7.4.3"
        source: pull

    - name: Run Redis container
      community.docker.docker_container:
        name: redis-app
        image: redis:7.4.3
        state: started
        restart_policy: always
        published_ports:
          - "6379:6379"

    - name: Pull Apache image
      community.docker.docker_image:
        name: httpd
        tag: "2.4.63"
        source: pull

    - name: Run Apache container
      community.docker.docker_container:
        name: httpd-app
        image: httpd:2.4.63
        state: started
        restart_policy: always
        published_ports:
          - "8082:80"
